// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asm.Models;

#nullable disable

namespace asm.Migrations
{
    [DbContext(typeof(AsmPcContext))]
    partial class AsmPcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("asm.Models.AnhSanPham", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnh"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LaAnhChinh")
                        .HasColumnType("bit");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaAnh")
                        .HasName("PK__AnhSanPh__356240DF82D123E2");

                    b.HasIndex("MaSp");

                    b.ToTable("AnhSanPham", (string)null);
                });

            modelBuilder.Entity("asm.Models.BaoCaoDoanhThu", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("TongDoanhThu")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int>("TongDonHang")
                        .HasColumnType("int");

                    b.HasKey("MaBaoCao")
                        .HasName("PK__BaoCaoDo__25A9188CD8CD6738");

                    b.HasIndex("MaNv");

                    b.ToTable("BaoCaoDoanhThu", (string)null);
                });

            modelBuilder.Entity("asm.Models.Benchmark", b =>
                {
                    b.Property<int>("MaBm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaBM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBm"));

                    b.Property<string>("CongCuTest")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("DiemSo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiBm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiBM");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<DateTime>("NgayTest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaBm")
                        .HasName("PK__Benchmar__272475AC9DBBE8BB");

                    b.HasIndex("MaSp");

                    b.ToTable("Benchmark", (string)null);
                });

            modelBuilder.Entity("asm.Models.Build", b =>
                {
                    b.Property<int>("MaBuild")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBuild"));

                    b.Property<bool>("CongKhai")
                        .HasColumnType("bit");

                    b.Property<int>("LuotThich")
                        .HasColumnType("int");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenBuild")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TongGia")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int?>("TongWatt")
                        .HasColumnType("int");

                    b.HasKey("MaBuild")
                        .HasName("PK__Build__B4A44200BA6BCFDE");

                    b.HasIndex("MaKh");

                    b.ToTable("Build", (string)null);
                });

            modelBuilder.Entity("asm.Models.ChiTietBuild", b =>
                {
                    b.Property<int>("MaCtb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTB");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtb"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaBuild")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("MaCtb")
                        .HasName("PK__ChiTietB__3DCB540B2BDEA9D3");

                    b.HasIndex("MaSp");

                    b.HasIndex(new[] { "MaBuild", "MaSp" }, "UQ__ChiTietB__66D61280DA33EC1D")
                        .IsUnique();

                    b.ToTable("ChiTietBuild", (string)null);
                });

            modelBuilder.Entity("asm.Models.ChiTietChucNang", b =>
                {
                    b.Property<int>("MaCtcn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTCN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtcn"));

                    b.Property<int>("MaCn")
                        .HasColumnType("int")
                        .HasColumnName("MaCN");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateTime>("NgayCapQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaCtcn")
                        .HasName("PK__ChiTietC__1E4E48DFCE9F3468");

                    b.HasIndex("MaCn");

                    b.HasIndex(new[] { "MaNv", "MaCn" }, "UQ__ChiTietC__D5578FEB6124A8D3")
                        .IsUnique();

                    b.ToTable("ChiTietChucNang", (string)null);
                });

            modelBuilder.Entity("asm.Models.ChiTietDanhMucSp", b =>
                {
                    b.Property<int>("MaCtdm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTDM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtdm"));

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.HasKey("MaCtdm")
                        .HasName("PK__ChiTietD__1E4E40FF7CE0C26A");

                    b.HasIndex("MaSp");

                    b.HasIndex(new[] { "MaDanhMuc", "MaSp" }, "UQ__ChiTietD__61075807B0AB6E5B")
                        .IsUnique();

                    b.ToTable("ChiTietDanhMucSP", (string)null);
                });

            modelBuilder.Entity("asm.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaCtgh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTGH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtgh"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int>("MaGh")
                        .HasColumnType("int")
                        .HasColumnName("MaGH");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(26, 2)")
                        .HasComputedColumnSql("([SoLuong]*[DonGia])", true);

                    b.HasKey("MaCtgh")
                        .HasName("PK__ChiTietG__1E4FAF542E60E9FE");

                    b.HasIndex("MaSp");

                    b.HasIndex(new[] { "MaGh", "MaSp" }, "UQ__ChiTietG__F557FE05DF855DED")
                        .IsUnique();

                    b.ToTable("ChiTietGioHang", (string)null);
                });

            modelBuilder.Entity("asm.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaCthd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCthd"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(26, 2)")
                        .HasComputedColumnSql("([SoLuong]*[DonGia])", true);

                    b.HasKey("MaCthd")
                        .HasName("PK__ChiTietH__1E4FA7710E7E44A4");

                    b.HasIndex("MaSp");

                    b.HasIndex(new[] { "MaHd", "MaSp" }, "UQ__ChiTietH__F557F660137C9172")
                        .IsUnique();

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("asm.Models.ChiTietThongBao", b =>
                {
                    b.Property<int>("MaCttb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTTB");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCttb"));

                    b.Property<bool>("DaXem")
                        .HasColumnType("bit");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int>("MaTb")
                        .HasColumnType("int")
                        .HasColumnName("MaTB");

                    b.Property<DateTime>("NgayNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaCttb")
                        .HasName("PK__ChiTietT__1E4FC51EF774303B");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaTb");

                    b.ToTable("ChiTietThongBao", (string)null);
                });

            modelBuilder.Entity("asm.Models.ChucNang", b =>
                {
                    b.Property<int>("MaCn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCn"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaCn")
                        .HasName("PK__ChucNang__27258E0E9456497D");

                    b.ToTable("ChucNang", (string)null);
                });

            modelBuilder.Entity("asm.Models.DanhGium", b =>
                {
                    b.Property<int>("MaDg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDg"));

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<DateTime>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("MaDg")
                        .HasName("PK__DanhGia__2725866018BBB931");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaSp");

                    b.HasIndex(new[] { "MaKh", "MaSp" }, "UQ__DanhGia__F5579F9E508AD176")
                        .IsUnique();

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("asm.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaDanhMuc")
                        .HasName("PK__DanhMuc__B3750887B2A58642");

                    b.HasIndex(new[] { "Slug" }, "UQ__DanhMuc__BC7B5FB6D8AF0494")
                        .IsUnique();

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("asm.Models.DiaChi", b =>
                {
                    b.Property<int>("MaDc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDc"));

                    b.Property<string>("DiaChiDay")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<bool>("MacDinh")
                        .HasColumnType("bit");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TinhThanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDc")
                        .HasName("PK__DiaChi__27258664E4123622");

                    b.HasIndex("MaKh");

                    b.ToTable("DiaChi", (string)null);
                });

            modelBuilder.Entity("asm.Models.GiaTungShop", b =>
                {
                    b.Property<int>("MaGts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGTS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGts"));

                    b.Property<bool>("ConHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenShop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaGts")
                        .HasName("PK__GiaTungS__3CD364FEFF449073");

                    b.HasIndex("MaSp");

                    b.ToTable("GiaTungShop", (string)null);
                });

            modelBuilder.Entity("asm.Models.GioHang", b =>
                {
                    b.Property<int>("MaGh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGh"));

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaGh")
                        .HasName("PK__GioHang__2725AE85C91B5164");

                    b.HasIndex(new[] { "MaKh" }, "UQ__GioHang__2725CF1F43B5B440")
                        .IsUnique();

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("asm.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<int?>("MaBaoCao")
                        .HasColumnType("int");

                    b.Property<int?>("MaDc")
                        .HasColumnType("int")
                        .HasColumnName("MaDC");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<DateTime>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ xác nhận");

                    b.HasKey("MaHd")
                        .HasName("PK__HoaDon__2725A6E05B02752E");

                    b.HasIndex("MaBaoCao");

                    b.HasIndex("MaDc");

                    b.HasIndex("MaKh");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("asm.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E38BE2BFE");

                    b.HasIndex(new[] { "Username" }, "UQ__KhachHan__536C85E491C1BECE")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__KhachHan__A9D105342F6369F2")
                        .IsUnique();

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("asm.Models.Kho", b =>
                {
                    b.Property<int>("MaKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKho"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKho")
                        .HasName("PK__Kho__3BDA935069FFA161");

                    b.ToTable("Kho", (string)null);
                });

            modelBuilder.Entity("asm.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNCC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNcc"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNcc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNCC");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaNcc")
                        .HasName("PK__NhaCungC__3A185DEB82E6A929");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("asm.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"));

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Luong")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenTk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenTK");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70A5D888752");

                    b.HasIndex(new[] { "TenTk" }, "UQ__NhanVien__4CF9E777BB23C81B")
                        .IsUnique();

                    b.HasIndex(new[] { "Cccd" }, "UQ__NhanVien__A955A0AA72823FCE")
                        .IsUnique()
                        .HasFilter("[CCCD] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__NhanVien__A9D105345235AC39")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("asm.Models.QuanLySanPham", b =>
                {
                    b.Property<int>("MaQl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaQL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQl"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaKho")
                        .HasColumnType("int");

                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<DateTime>("NgayQuanLy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQl")
                        .HasName("PK__QuanLySa__2725F852CB48FE1F");

                    b.HasIndex("MaKho");

                    b.HasIndex("MaSp");

                    b.HasIndex(new[] { "MaNv", "MaSp" }, "UQ__QuanLySa__F557878A56D763F4")
                        .IsUnique();

                    b.ToTable("QuanLySanPham", (string)null);
                });

            modelBuilder.Entity("asm.Models.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int?>("MaNcc")
                        .HasColumnType("int")
                        .HasColumnName("MaNCC");

                    b.Property<int?>("MaNvquanLy")
                        .HasColumnType("int")
                        .HasColumnName("MaNVQuanLy");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("datetime");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenSP");

                    b.Property<string>("ThongSoKyThuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThuongHieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081CB2331181");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaNcc");

                    b.HasIndex("MaNvquanLy");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("asm.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaGd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGd"));

                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ thanh toán");

                    b.HasKey("MaGd")
                        .HasName("PK__ThanhToa__2725AE816E54C71C");

                    b.HasIndex("MaHd");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("asm.Models.ThongBao", b =>
                {
                    b.Property<int>("MaTb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTB");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTb"));

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chưa đọc");

                    b.HasKey("MaTb")
                        .HasName("PK__ThongBao__2725006F950812E7");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("asm.Models.TuongThich", b =>
                {
                    b.Property<int>("MaTt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTt"));

                    b.Property<int>("MaDanhMucA")
                        .HasColumnType("int");

                    b.Property<int>("MaDanhMucB")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ThuocTinhA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThuocTinhB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTt")
                        .HasName("PK__TuongThi__27250079E4C91C81");

                    b.HasIndex("MaDanhMucA");

                    b.HasIndex("MaDanhMucB");

                    b.ToTable("TuongThich", (string)null);
                });

            modelBuilder.Entity("asm.Models.AnhSanPham", b =>
                {
                    b.HasOne("asm.Models.SanPham", "MaSpNavigation")
                        .WithMany("AnhSanPhams")
                        .HasForeignKey("MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__AnhSanPham__MaSP__07C12930");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("asm.Models.BaoCaoDoanhThu", b =>
                {
                    b.HasOne("asm.Models.NhanVien", "MaNvNavigation")
                        .WithMany("BaoCaoDoanhThus")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__BaoCaoDoan__MaNV__3D2915A8");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("asm.Models.Benchmark", b =>
                {
                    b.HasOne("asm.Models.SanPham", "MaSpNavigation")
                        .WithMany("Benchmarks")
                        .HasForeignKey("MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Benchmark__MaSP__29221CFB");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("asm.Models.Build", b =>
                {
                    b.HasOne("asm.Models.KhachHang", "MaKhNavigation")
                        .WithMany("Builds")
                        .HasForeignKey("MaKh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Build__MaKH__1BC821DD");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("asm.Models.ChiTietBuild", b =>
                {
                    b.HasOne("asm.Models.Build", "MaBuildNavigation")
                        .WithMany("ChiTietBuilds")
                        .HasForeignKey("MaBuild")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietBu__MaBui__245D67DE");

                    b.HasOne("asm.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietBuilds")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietBui__MaSP__25518C17");

                    b.Navigation("MaBuildNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("asm.Models.ChiTietChucNang", b =>
                {
                    b.HasOne("asm.Models.ChucNang", "MaCnNavigation")
                        .WithMany("ChiTietChucNangs")
                        .HasForeignKey("MaCn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietChu__MaCN__693CA210");

                    b.HasOne("asm.Models.NhanVien", "MaNvNavigation")
                        .WithMany("ChiTietChucNangs")
                        .HasForeignKey("MaNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietChu__MaNV__68487DD7");

                    b.Navigation("MaCnNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("asm.Models.ChiTietDanhMucSp", b =>
                {
                    b.HasOne("asm.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("ChiTietDanhMucSps")
                        .HasForeignKey("MaDanhMuc")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDa__MaDan__0D7A0286");

                    b.HasOne("asm.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietDanhMucSps")
                        .HasForeignKey("MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDan__MaSP__0E6E26BF");

                    b.Navigation("MaDanhMucNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("asm.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("asm.Models.GioHang", "MaGhNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietGio__MaGH__37703C52");

                    b.HasOne("asm.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietGio__MaSP__3864608B");

                    b.Navigation("MaGhNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("asm.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("asm.Models.HoaDon", "MaHdNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHoa__MaHD__4B7734FF");

                    b.HasOne("asm.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHoa__MaSP__4C6B5938");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("asm.Models.ChiTietThongBao", b =>
                {
                    b.HasOne("asm.Models.KhachHang", "MaKhNavigation")
                        .WithMany("ChiTietThongBaos")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietTho__MaKH__625A9A57");

                    b.HasOne("asm.Models.ThongBao", "MaTbNavigation")
                        .WithMany("ChiTietThongBaos")
                        .HasForeignKey("MaTb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietTho__MaTB__6166761E");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaTbNavigation");
                });

            modelBuilder.Entity("asm.Models.DanhGium", b =>
                {
                    b.HasOne("asm.Models.HoaDon", "MaHdNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaHd")
                        .HasConstraintName("FK__DanhGia__MaHD__56E8E7AB");

                    b.HasOne("asm.Models.KhachHang", "MaKhNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__DanhGia__MaKH__55009F39");

                    b.HasOne("asm.Models.SanPham", "MaSpNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__DanhGia__MaSP__55F4C372");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("asm.Models.DiaChi", b =>
                {
                    b.HasOne("asm.Models.KhachHang", "MaKhNavigation")
                        .WithMany("DiaChis")
                        .HasForeignKey("MaKh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DiaChi__MaKH__73BA3083");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("asm.Models.GiaTungShop", b =>
                {
                    b.HasOne("asm.Models.SanPham", "MaSpNavigation")
                        .WithMany("GiaTungShops")
                        .HasForeignKey("MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__GiaTungSho__MaSP__2CF2ADDF");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("asm.Models.GioHang", b =>
                {
                    b.HasOne("asm.Models.KhachHang", "MaKhNavigation")
                        .WithOne("GioHang")
                        .HasForeignKey("asm.Models.GioHang", "MaKh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__GioHang__MaKH__32AB8735");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("asm.Models.HoaDon", b =>
                {
                    b.HasOne("asm.Models.BaoCaoDoanhThu", "MaBaoCaoNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaBaoCao")
                        .HasConstraintName("FK__HoaDon__MaBaoCao__43D61337");

                    b.HasOne("asm.Models.DiaChi", "MaDcNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaDc")
                        .HasConstraintName("FK__HoaDon__MaDC__44CA3770");

                    b.HasOne("asm.Models.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDon__MaKH__42E1EEFE");

                    b.Navigation("MaBaoCaoNavigation");

                    b.Navigation("MaDcNavigation");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("asm.Models.QuanLySanPham", b =>
                {
                    b.HasOne("asm.Models.Kho", "MaKhoNavigation")
                        .WithMany("QuanLySanPhams")
                        .HasForeignKey("MaKho")
                        .HasConstraintName("FK__QuanLySan__MaKho__14270015");

                    b.HasOne("asm.Models.NhanVien", "MaNvNavigation")
                        .WithMany("QuanLySanPhams")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__QuanLySanP__MaNV__123EB7A3");

                    b.HasOne("asm.Models.SanPham", "MaSpNavigation")
                        .WithMany("QuanLySanPhams")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__QuanLySanP__MaSP__1332DBDC");

                    b.Navigation("MaKhoNavigation");

                    b.Navigation("MaNvNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("asm.Models.SanPham", b =>
                {
                    b.HasOne("asm.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .IsRequired()
                        .HasConstraintName("FK__SanPham__MaDanhM__00200768");

                    b.HasOne("asm.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNcc")
                        .HasConstraintName("FK__SanPham__MaNCC__01142BA1");

                    b.HasOne("asm.Models.NhanVien", "MaNvquanLyNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNvquanLy")
                        .HasConstraintName("FK__SanPham__MaNVQua__04E4BC85");

                    b.Navigation("MaDanhMucNavigation");

                    b.Navigation("MaNccNavigation");

                    b.Navigation("MaNvquanLyNavigation");
                });

            modelBuilder.Entity("asm.Models.ThanhToan", b =>
                {
                    b.HasOne("asm.Models.HoaDon", "MaHdNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaHd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ThanhToan__MaHD__503BEA1C");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("asm.Models.ThongBao", b =>
                {
                    b.HasOne("asm.Models.KhachHang", "MaKhNavigation")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__ThongBao__MaKH__5BAD9CC8");

                    b.HasOne("asm.Models.NhanVien", "MaNvNavigation")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__ThongBao__MaNV__5CA1C101");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("asm.Models.TuongThich", b =>
                {
                    b.HasOne("asm.Models.DanhMuc", "MaDanhMucANavigation")
                        .WithMany("TuongThichMaDanhMucANavigations")
                        .HasForeignKey("MaDanhMucA")
                        .IsRequired()
                        .HasConstraintName("FK__TuongThic__MaDan__17F790F9");

                    b.HasOne("asm.Models.DanhMuc", "MaDanhMucBNavigation")
                        .WithMany("TuongThichMaDanhMucBNavigations")
                        .HasForeignKey("MaDanhMucB")
                        .IsRequired()
                        .HasConstraintName("FK__TuongThic__MaDan__18EBB532");

                    b.Navigation("MaDanhMucANavigation");

                    b.Navigation("MaDanhMucBNavigation");
                });

            modelBuilder.Entity("asm.Models.BaoCaoDoanhThu", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("asm.Models.Build", b =>
                {
                    b.Navigation("ChiTietBuilds");
                });

            modelBuilder.Entity("asm.Models.ChucNang", b =>
                {
                    b.Navigation("ChiTietChucNangs");
                });

            modelBuilder.Entity("asm.Models.DanhMuc", b =>
                {
                    b.Navigation("ChiTietDanhMucSps");

                    b.Navigation("SanPhams");

                    b.Navigation("TuongThichMaDanhMucANavigations");

                    b.Navigation("TuongThichMaDanhMucBNavigations");
                });

            modelBuilder.Entity("asm.Models.DiaChi", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("asm.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("asm.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("DanhGia");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("asm.Models.KhachHang", b =>
                {
                    b.Navigation("Builds");

                    b.Navigation("ChiTietThongBaos");

                    b.Navigation("DanhGia");

                    b.Navigation("DiaChis");

                    b.Navigation("GioHang");

                    b.Navigation("HoaDons");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("asm.Models.Kho", b =>
                {
                    b.Navigation("QuanLySanPhams");
                });

            modelBuilder.Entity("asm.Models.NhaCungCap", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("asm.Models.NhanVien", b =>
                {
                    b.Navigation("BaoCaoDoanhThus");

                    b.Navigation("ChiTietChucNangs");

                    b.Navigation("QuanLySanPhams");

                    b.Navigation("SanPhams");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("asm.Models.SanPham", b =>
                {
                    b.Navigation("AnhSanPhams");

                    b.Navigation("Benchmarks");

                    b.Navigation("ChiTietBuilds");

                    b.Navigation("ChiTietDanhMucSps");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("DanhGia");

                    b.Navigation("GiaTungShops");

                    b.Navigation("QuanLySanPhams");
                });

            modelBuilder.Entity("asm.Models.ThongBao", b =>
                {
                    b.Navigation("ChiTietThongBaos");
                });
#pragma warning restore 612, 618
        }
    }
}
